import type { Metadata } from "next";
import { Playfair_Display_SC, Amita, Anton_SC } from "next/font/google";
import loacalFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const PlayfairDisplaySC = Playfair_Display_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-playfair-display-sc",
});

const antonSC = Anton_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton-sc",
});

const amita = Amita({
  subsets: ["devanagari"],
  weight: "400",
  variable: "--font-amita",
});

const sacramento = loacalFont({
  src: [
    {
      path: "../public/fonts/sacramento/Sacramento.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-sacramento",
});

const moms_typewriter = loacalFont({
  src: [
    {
      path: "../public/fonts/moms_typewriter/Mom«t___.ttf",
    },
  ],
  variable: "--font-moms-typewriter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${moms_typewriter.variable} ${sacramento.variable} ${PlayfairDisplaySC.variable} ${amita.variable} ${antonSC.variable} antialiased bg-zinc-950 text-zinc-100 min-h-screen flex flex-col`}
      >
        <div className="relative z-20">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
